"""Assemble bilingual daily reports with guaranteed citation metadata."""
from datetime import datetime
from typing import Any, Dict, List, Optional


def pubmed_url(pmid: str) -> str:
    return f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/"


def doi_url(doi: Optional[str]) -> str:
    if not doi:
        return ""
    return f"https://doi.org/{doi}"


def pmc_url(pmcid: Optional[str]) -> str:
    if not pmcid:
        return ""
    clean = pmcid if pmcid.upper().startswith("PMC") else f"PMC{pmcid}"
    return f"https://www.ncbi.nlm.nih.gov/pmc/articles/{clean}/"


def fulltext_label(paper: Dict[str, Any]) -> str:
    source = (paper.get("full_text_source") or "").lower()
    if paper.get("has_pdf") or source == "pdf":
        return "PDF 全文 / Full PDF"
    if source in ("pmc_xml", "jats"):
        return "PMC 全文 XML / PMC full text"
    return "僅摘要 / Abstract only"


def source_card_markdown(paper: Dict[str, Any], index: int) -> str:
    pmid = str(paper.get("pmid") or "")
    pmcid = paper.get("pmcid") or ""
    doi = paper.get("doi") or ""
    title = (paper.get("title") or "Untitled").replace("\n", " ").strip()
    journal = paper.get("journal") or "Unknown journal"
    pub_date = paper.get("pub_date") or "Unknown date"
    authors = paper.get("authors") or "Unknown authors"
    pmid_link = pubmed_url(pmid)
    doi_md = f"[{doi}]({doi_url(doi)})" if doi else "—"
    pmc_md = f"[{pmcid}]({pmc_url(pmcid)})" if pmcid else "—"

    return f"""### {index}. {title}

| 欄位 Field | 內容 Content |
|---|---|
| **期刊 Journal** | {journal} |
| **發表日期 Published** | {pub_date} |
| **PubMed ID** | [{pmid}]({pmid_link}) |
| **PMC ID** | {pmc_md} |
| **DOI** | {doi_md} |
| **作者 Authors** | {authors} |
| **全文來源 Full text** | {fulltext_label(paper)} |
| **連結 Links** | [PubMed]({pmid_link}){f' · [PMC]({pmc_url(pmcid)})' if pmcid else ''}{f' · [DOI]({doi_url(doi)})' if doi else ''} |
"""


def source_index_table(papers: List[Dict[str, Any]]) -> str:
    rows = []
    for i, p in enumerate(papers, 1):
        pmid = str(p.get("pmid") or "")
        title = (p.get("title") or "Untitled").replace("|", "/").replace("\n", " ").strip()
        if len(title) > 90:
            title = title[:87] + "…"
        journal = (p.get("journal") or "—").replace("|", "/")
        pub_date = p.get("pub_date") or "—"
        doi = p.get("doi") or ""
        doi_cell = f"[{doi}]({doi_url(doi)})" if doi else "—"
        rows.append(
            f"| {i} | {title} | {journal} | {pub_date} | "
            f"[{pmid}]({pubmed_url(pmid)}) | {doi_cell} | {fulltext_label(p)} |"
        )
    header = (
        "| # | 標題 Title | 期刊 Journal | 發表日期 Date | PubMed | DOI | 全文 |\n"
        "|---|---|---|---|---|---|---|"
    )
    return header + "\n" + "\n".join(rows)


def build_bilingual_report(
    papers: List[Dict[str, Any]],
    paper_analyses: List[str],
    zh_digest: str,
    en_digest: str,
    query_keyword: str,
    model_name: str,
    date_str: Optional[str] = None,
) -> str:
    date_str = date_str or datetime.now().strftime("%Y-%m-%d")
    cards = "\n".join(source_card_markdown(p, i) for i, p in enumerate(papers, 1))
    per_paper = []
    for i, (p, analysis) in enumerate(zip(papers, paper_analyses), 1):
        per_paper.append(source_card_markdown(p, i))
        per_paper.append((analysis or "").strip() or "*(分析未產出 / Analysis unavailable)*")
        per_paper.append("---")

    zh_body = (zh_digest or "").strip()
    en_body = (en_digest or "").strip()

    return f"""# 每日文獻綜述 / Daily Literature Digest — {date_str}

**主題 Topic:** `{query_keyword}`  
**模型 Model:** `{model_name}`  
**篇數 Papers:** {len(papers)} 篇（已去重 / deduplicated）

> 來源資訊（期刊、發表日期、PubMed ID）由 PubMed 結構化欄位寫入，不依賴語言模型。  
> Source metadata is taken from PubMed records, not generated by the LLM.

---

## 文獻來源索引 / Article Source Index

{source_index_table(papers)}

### 完整書目 / Full citations

{cards}

---

<div class="report-lang" data-lang="zh">

# 中文綜述

{zh_body}

## 逐篇分析（中英）

{"".join(per_paper)}

</div>

<div class="report-lang" data-lang="en">

# English Digest

{en_body}

## Individual papers (with sources)

{"".join(per_paper)}

</div>

---

*Generated locally with Ollama `{model_name}` · {datetime.now().strftime("%Y-%m-%d %H:%M")} (Asia/Taipei)*
"""
